POST http://localhost:9999/banners.save?id=0&title=Some Title text&content=Some content text&button=Check&link=https://alif.tj/deposit#CountYourIncome
###
GET http://127.0.0.1:9999/banners.getAll
# Accept: application/json

###
GET http://127.0.0.1:9999/banners.getById?id=1
Accept: application/json